service:
  name: "test_service"
  fqdnOrIP: "127.0.0.1"
  apiPort: "8000"
  rpcPort: "8001"
logging:
  logDir: ""
  logFile: "test_service.log"
  loggingLevel: "info"
sql_db:
  fqdnOrIP: "127.0.0.1"
  port: "5432"
  username: "postgres"
  password: ""
  dbName: "test-db"
kvstore:
  fqdnOrIP: "127.0.0.1"
  port: "2379"
